# Generated by Django 5.0.6 on 2026-09-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='publication_date',
            new_name='pub_date',
        ),
    ]
